version: "3.9"
secrets:
    db_password:
        file: ./db_password.secret
    smtp_server:
        file: ./smtp_server.secret
    smtp_port:
        file: ./smtp_port.secret
    smtp_username:
        file: ./smtp_username.secret
    smtp_password:
        file: ./smtp_password.secret
    email_from:
        file: ./email_from.secret
volumes:
    db_data:
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
        volumes:
            - "db_data:/var/lib/postgresql/data"
            - type: bind
              source: "./docker-entrypoint-initdb.d"
              target: "/docker-entrypoint-initdb.d"
        expose:
            - 5432
        secrets:
            - db_password
    channel_builder:
        build:
            context: ..
            dockerfile: docker/Dockerfile-testing
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
            POSTGRES_HOST: "db:5432"
            CB_LISTEN: "0.0.0.0:3031"
            FRONTEND_LOC: "http://192.168.7.31:8080"
            SMTP_SERVER_FILE: /run/secrets/smtp_server
            SMTP_PORT_FILE: /run/secrets/smtp_port
            SMTP_USERNAME_FILE: /run/secrets/smtp_username
            SMTP_PASSWORD_FILE: /run/secrets/smtp_password
            EMAIL_FROM_ADDR_FILE: /run/secrets/email_from
            RUST_BACKTRACE: 1
        ports:
            - 3031:3031
        secrets:
            - db_password
            - smtp_server
            - smtp_port
            - smtp_username
            - smtp_password
            - email_from
    web:
        image: nginx
        volumes:
            - ../frontend/content:/usr/share/nginx/html:ro
        ports:
            - 8080:80
